version: "3.2"

services:
  api:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    ports:
      - "8000:80"
    depends_on:
      - "db"
  db:
    build:
      dockerfile: ./Dockerfile.mysql
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: plsnohack
